name: mlops-workshop-d2d

channels:
    - conda-forge

dependencies:
  - pip
  - pip:
    - tensorflow
    - dtreeviz
    - lrcurve
    - causalgraphicalmodels
  - python=3.8
  - scikit-learn
  - pandas
  - seaborn
  - jupyter
  - notebook
  - numpy
  - matplotlib
  - evidently
  - prometheus_client
  - Flask
  - flask_cors
  - Werkzeug
  - requests
  - pyyaml
  - scipy

